export const REQUEST_TASKS = "REQUEST_TASKS";
export const REQUEST_TASKS_SUCCESS = "REQUEST_TASKS_SUCCESS";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_REQUEST_SUCCESS = "ADD_TASK_REQUEST_SUCCESS";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
